### ISSUE TITLE
Reopening or migrating rescripts?

### ISSUE THREAD

**Issue by YPCrumble** [paritytech/capi#110]
@harrysolovay so sorry to message you here but I couldn't do it on the Rescripts repo. 

I've been using this in production since it was built, and it has always been the simplest and most effective CRA tool. It's the only one that seems to use plain vanilla JS and the KISS method.

In any case, every other library seems to have come and gone and this is the only one that works for me on CRA v5. Would you consider reopening it and/or transferring it? I'd be happy to take over development as I'm using it in production for https://bookclubs.com.

Thank you for considering it!

Sincerely,

Ian Campbell (@YPCrumble)

**Comment by harrysolovay** [comment]
Hi @YPCrumble, thank you for the kind words about Rescripts. Unfortunately––given the amount of time that has passed since writing Rescripts (~4 years)––I can't vouch for its ongoing stability (hence why Rescripts is archived).

Regarding transferring it––I'd rather not; many projects still depend on Rescripts and I feel that it would be unkind to existing users for me to transfer ownership.

In the future, please don't open issues in this repo. If you need to get in touch, please message me directly [on Twitter](https://twitter.com/harrysolovay).

And again, thank you for the kind words about Rescripts. I'm thrilled to hear that it was/is useful to you.
