### ISSUE TITLE
why isn't `examples/tx/balances_transfer.eg.ts` failing?

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#1108]
Should be failing given that the free balance `run`s reference the same rune instance (hence, the `>` assertion between the two should fail).

**Comment by tjjfvi** [comment]
Because the two are run sequentially (not in parallel), the `Run`s are cleaned up in the interim, clearing the memoization and causing it to run fresh the second time around. This behavior should be valid for anything that is idempotent (and not time-dependent).

Anything that is time-dependent should be represented as such within Rune, which will mean that no matter if it is cleaned up or not, the behavior will remain correct. In other words, rather than leaving the `blockHash` parameter as defaulting to the latest block (at the time of execution), it should default to a subscription to the latest block.

The way we handle certain things are are not time-dependent but are also not idempotent (for example, `createDevUsers`) is still to be determined. Likely, such `Run`s will not be cleaned up until the corresponding `Rune` is GC'd.
