### ISSUE TITLE
unable to encode latest metadata with `metadata` codec

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#21]
Given https://gist.github.com/ryanleecode/c0d2b7322f2252378dc50a969bd88772 as the latest metadata. Using `metadata` from substrate codec to encode it fails with:

```
file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:350
var VectorEnc = (inner, size) => size >= 0 ? (value) => mergeUint8(...value.map(inner)) : (value) => mergeUint8(compact.enc(value.length), ...value.map(inner));
                                                                                                                                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Array.<anonymous> (file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:350:131)
    at file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:331:99
    at Array.map (<anonymous>)
    at file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:331:66
    at file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:93:54
    at Array.map (<anonymous>)
    at Array.<anonymous> (file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:350:149)
    at file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:331:99
    at Array.map (<anonymous>)
    at file:///home/ryan/Documents/Repositories/capi/node_modules/scale-ts/dist/scale-ts.mjs:331:66

Node.js v20.3.1
```

**Comment by josepot** [comment]
I've tried to [reproduce the issue and everything seems to be working fine](https://github.com/paritytech/capi/blob/test-broken-meta/packages/experiments/src/main.ts) 🤔.

Please have a look at the [`test-broken-meta` branch](https://github.com/paritytech/capi/tree/test-broken-meta), that branch was created after the current `main` branch and basically what it has is a new package named `experiments`, which is what I've been using for running different sorts of experiments... Since I already had [some code for getting the latest metadata from smoldot](https://github.com/paritytech/capi/blob/test-broken-meta/packages/experiments/src/getMetadata.ts), the only thing that I had to do was to try to re-encoded, and everything [seems to be working well](https://github.com/paritytech/capi/blob/test-broken-meta/packages/experiments/src/main.ts#L10).

In order to reproduce it, do this: checkout the `test-broken-meta` branch, run `npm i` from the root, then run `npm run build` (also from the root), and then go to `packages/experimets` and from inside that path run `npm start`.

Please fee free to make the necessary changes to reproduce the issue.

If I had to make a guess about what could have happened here, is that perhaps that `latest-metadata.json` file was generated with an old version of the `metadata` codec. Please keep in mind that the metadata codec [has recently changed](https://github.com/paritytech/capi/pull/20). So, if that file was created with the prior codec, then it wont work with the current one.

PS: I will be creating a PR later today to add the `experiments` package into the repo, so that we have a common playground for testing things. That should make everything easier: not just to test stuff, but also to show issues and/or ideas.

**Comment by josepot** [comment]
> If I had to make a guess about what could have happened here, is that perhaps that latest-metadata.json file was generated with an old version of the metadata codec. Please keep in mind that the metadata codec https://github.com/paritytech/capi/pull/20. So, if that file was created with the prior codec, then it wont work with the current one.

Yeah, that's what happened: https://gist.github.com/ryanleecode/c0d2b7322f2252378dc50a969bd88772#file-latest_metadata-json-L9-L24

**Comment by ryanleecode** [comment]
Yup that was indeed the issue. thx for investigating
