### ISSUE TITLE
Extracting Extrinsic Events

### ISSUE THREAD

**Issue by jainkrati** [paritytech/capi#272]
**Updated Issue Body**:

What would enable simplest interaction with extrinsic events?

Some rough ideas:

Extracting emitted events after finalization:

```ts
import * as P from "./generated.ts";

const events = await P.balances.transfer({ from, to })
  .signed(signFn)
  .sent
  .finalized
  .events
  .run();

if (events instanceof Error) throw events;

for (const event of events) {
  // use it
}
```

Note the declarative naming / sequence of methods/getters.

---

**Original Issue Body**:

New developers are unaware of how polkadot and parachain apis propagate errors / results and any additional logics for determining the exact root cause of the error or exact confirmation of successful transaction. 

If Capi had a getDetailedResult() method which does the same logic behind the scenes then DX would be so much better and Capi adoption would increase as well. Usage would be:

`methodName().call().getDetailedResult()`

Attaching screenshot from one of the polkadot Element channels which supports this use case:
<img width="835" alt="Screenshot 2022-09-29 at 2 35 02 PM" src="https://user-images.githubusercontent.com/7895856/193575200-f2f46618-50ea-4264-a4e7-405159cd1ccd.png">

**Comment by jsdw** [comment]
Subxt does a very similar thing to what you propose (the example https://github.com/paritytech/subxt/blob/master/examples/examples/submit_and_watch.rs#L67 illustrates this best I think).

Basically we allow something like:

```rust
let balance_transfer_events = api
        .tx()
        // submit some TX:
        .sign_and_submit_then_watch_default(&balance_transfer_tx, &signer)
        .await?
        // wait for the finalized transfer event which has the block hash in
        // and also get events to check for the ExtrinsicSuccess:
        .wait_for_finalized_success()
        .await?;

// balance_transfer_events is a struct containing event details and here
// you can iterate over the events related to the extrinsic and decode them
// and such, or search them etc..
let failed_event =
        balance_transfer_events.find_first::<polkadot::system::events::ExtrinsicFailed>()?;

for event in balance_transfer_events.iter() {
    // ....
}
```

My general feeling and approach is to make sure that everything is exposed in each stage (so instead of `.wait_for_finalized_success()` somebody can just stream the transaction events themselves and react to each one as the tx makes progress, and they can just wait for the tx to be finalized and then fetch the events from that themselves and not worry about the ExtrinsicSuccess one, or whatever else.

And of course, while exposing each of the stages it's nice having a high level "common" API :)

All that said, since you want to build up a computation description, your suggestion makes sense to me! Perhaps with some approach to easily verify that the ExtrinsicSuccess event was seen and the thing is fully "successful".

**Comment by jainkrati** [comment]
There are scenarios like [these](https://substrate.stackexchange.com/questions/584/how-to-know-if-the-extrinsic-completed-without-any-extrinsic-errors/585#585) where developer needs special handling to find error if using an extrinsic

**Comment by harrysolovay** [comment]
> My general feeling and approach is to make sure that everything is exposed in each stage

I completely agree with this. Thank you for the feedback @jsdw.

@jainkrati –– is it alright if I edit the title and body of this issue to reflect the topic of API design for extrinsic stage&event capture?

**Comment by jainkrati** [comment]
Sure @harrysolovay 👍

**Comment by harrysolovay** [comment]
Done as of #353 –– note to tweak API in #388
