### ISSUE TITLE
ensure examples run examples in Deno+puppeteer in CI

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#328]
We need a minimal way to test that simple examples run in the browser. This should take the form of a check that appropriately block merging upon fails.

Related

- #437

**Comment by tamrai** [comment]
Let me know what do you think about this approach ⤵️

#### Description:
- Build minimal light components to be rendered in the browser. Each component implements a separate CAPI example that can be tested by the _Browser e2e testing tool_ (eg. click-wait-view-check). 
- Create sever routes to cover each example (component) separately.

#### Actors:
-  CI Tests 
   - GitHub Actions
- CAPI server 
  - Host static files (bundle) or `deno run -A serve.ts` (to be imported by WebApp for a build)
- WebApp
  - Fresh + Preact (rendered client side / islands) ([https://fresh.deno.dev/docs/getting-started/adding-interactivity ns](https://fresh.deno.dev/docs/getting-started/adding-interactivity)) 
  - or Aleph.js (https://deno.land/manual@v1.29.2/basics/react)
- Sinco 
  - Browser testing automation tool (https://github.com/drashland/sinco)
  
#### Example flow:
![task](https://user-images.githubusercontent.com/7630720/211505767-b7c75ca1-ff42-454b-9bae-390a11691a74.png)

**Comment by harrysolovay** [comment]
Thanks for looking into this! I believe there's a simpler approach. My thoughts on your initial thinking:

> Build minimal light components to be rendered in the browser.

Why? I don't see how this is relevant; our only goal is to confirm that Capi examples can run in a browser environment in CI (why would test-specific components fit in?).

> Create sever routes to cover each example (component) separately.

Why not just one dynamic route that matches a given example?

```ts
const pattern = new URLPattern({ pathname: "/:example_file_path" })

pattern.exec('http://localhost:8001/examples/balance.ts').pathname.groups // `{ example_file_path: "examples/balance.ts" }`
```

In terms of actors...

> - CI Tests
>   - GitHub Actions

^ yes, this is a given

> - CAPI server

^ let's not couple the Capi server to a tiny HTTP server specifically tailored to CI browser testing

> - WebApp
>   - Fresh + Preact (rendered client side / islands ([https://fresh.deno.dev/docs/getting-started/adding-interactivity ns](https://fresh.deno.dev/docs/getting-started/adding-interactivity))
>  - or Aleph.js (https://deno.land/manual@v1.29.2/basics/react)

^ why do we need one of these frameworks? Hybrid rendering schemes seem heavy weight for our use case. **All we want to do is execute a Capi example in a browser context in CI**.

> - Sinco

I mentioned Sinco only as an example. Sinco hasn't seen a release since May 2022 / we can find an approach comprised of more standard tools (or perhaps none are necessary). If you look at what @tjjfvi mocked in #437, you'll notice that a basic browser testing approach was possible without use of any non-standard deps whatsoever. It'd be nice if we can keep it that way (unless you come across a high-quality tool for this use case).

**Comment by tamrai** [comment]
Thanks for the feedback and the comment!
Let's step back and try to unblock the first crucial step which is to run the example file in the browser environment.

### Example file

Used example file: [derived.ts](https://github.com/paritytech/capi/blob/main/examples/derived.ts)
```js
import * as C from "http://localhost:5646/@local/mod.ts" // 1) deno bundle
// import * as C from "../target/npm/esm/mod.js"  // 2) deno dnt & esbuild
// import { entryRead, polkadot, throwIfError, Z } from "../target/npm/esm/mod.js"

const ids = C.entryRead(C.polkadot)("Paras", "Parachains", [], {})
  .access("value")
  .as<number[]>()

const root = C.Z.each(ids, (id) => {
  return C.entryRead(C.polkadot)("Paras", "Heads", [id], {})
})

console.log(C.throwIfError(await root.run()))
```

### Run example file in the browser environment

1) Using: `deno bundle` - command won't work here because it's bundling for the deno environment.
- Error browser: deno bundled file output and bidings. eg `Uncaught ReferenceError: Cannot access 'mod7' before initialization`and/or deno bindings errors

- `deno bundle ./examples/derived.ts > ./examples/derived.js`
https://github.com/paritytech/capi/blob/cd9d395777ff3c2eacf4f2ef7edf3daa64b170c7/_tasks/run_browser.ts#L13

- https://deno.land/manual@v1.29.2/tools/bundler#bundling-for-the-web
  > The output of deno bundle is intended for consumption in Deno and not for use in a web browser or other runtimes. That said, depending on the input it may work in other environments.
  > If you wish to bundle for the web, we recommend other solutions such as [esbuild](https://esbuild.github.io/).

2) Using `dnt + esbuild` - it still won't work because now the target environment is node not a browser.

- `deno task run _tasks/dnt.ts` [task file](https://github.com/paritytech/capi/blob/main/_tasks/dnt.ts) / [deno modules for Node.js](https://github.com/denoland/dnt)
- `npx esbuild derived.ts --bundle --platform=node --outfile=derived.js` -> OK node
- `npx esbuild derived.ts --bundle --platform=browser --outfile=derived.js`
  -  Error, node bidings. eg `_Uncaught ReferenceError: require is not defined at. ../target/npm/node_modules/ws/lib/stream.js`_

 I will investigate further. Appreciate any thoughts on this!

**Comment by tjjfvi** [comment]
> Using: `deno bundle` - command won't work here because it's bundling for the deno environment.

The deno environment is close enough to the browser environment that it can be made to work.

The only change we'd have to make is to make sure that we're not using any `Deno` APIs – which is exactly what we want to do anyway.

> Error browser: deno bundled file output and bidings. eg `Uncaught ReferenceError: Cannot access 'mod7' before initialization` and/or deno bindings errors

If you looked into this error, you would find that it's produced by the following code:
```ts
const mod7 = {
    smoldot: mod6,
    TransactionStatus,
    ReturnFlags,
    ReturnFlags,
    smoldot: mod6,
    mod: mod7,
    TransactionStatus
};
```
Which is clearly invalid, independent of deno/browser. Indeed, running this via Deno produces the same error.

This is, to a degree, a bug in `deno bundle`, but it has an easy fix. That `mod7` was produced by `known/mod.ts`, which has this line:
```ts
export * from "./mod.ts"
```
This file is `export *`-ing from itself – which, while technically valid in ESM, is useless, and it's not unreasonable for `deno bundle` to fail in this case. Removing this line fixes this error, at which point the bundled file works perfectly both in Deno and in the browser:
![image](https://user-images.githubusercontent.com/44031566/212356098-3b596eee-0f29-4e2c-a571-1228d71b2a18.png)

---

It is worth noting that some of the examples will currently fail to run in the browser, as they attempt to spin up a dev chain, which currently hits a raw TCP server – not something the browser supports. Fixing this is out of the scope of this issue, and will likely be fixed along with #471. So for now, we just want to get the examples that don't depend on the dev chain server (e.g. `derived.ts`) working – it's fine if the rest error for now.

---

The question in this issue is not:
> How do we run the example in the browser?

We already have the answer to this – `deno bundle`.

The question is:
> How do we run the browser in the CI?

**Comment by tamrai** [comment]
Thanks a lot @tjjfvi for the answer and giving more info about Deno and Capi! I've applied your suggestions and all works!

**Comment by ryanleecode** [comment]
Looking into making the CLI generate a Deno test file for each example, then you can run  `deno test -A -L=info --parallel ./my-test-dir/*.ts` in CI to make them all run in parallel at the same time. :rocket: :fire:

**Comment by harrysolovay** [comment]
I like this idea quite a lot. Would be aided by #509.

**Comment by ryanleecode** [comment]
Hmm not sure if assertions would work as  i still plan to run the examples as a separate deno task. Could explore using the example code and embedding it in the "codegened" tests directly but i think that gets complicated

**Comment by ryanleecode** [comment]
https://github.com/denoland/deno_emit this may prove useful

**Comment by ryanleecode** [comment]
Having trouble with `deno bundle` since it outputs code that isnt compatible for browser. Even bundling `examples/derived.ts` (as mentioned above) produced this. 

https://gist.github.com/ryanleecode/7e3b7f2ea6e341067f0b3e3b25faf2a4

Deno team recommends using esbuild so will be looking into that

https://deno.land/manual@v1.31.0/tools/bundler
https://esbuild.github.io/

**Comment by ryanleecode** [comment]
> Why this is not recommended: Deno is newer than node, less widely used, and supports fewer platforms than node, so node is recommended as the primary way to run esbuild. Deno also uses the internet as a package system instead of existing JavaScript package ecosystems, and esbuild is designed around and optimized for npm-style package management. You should still be able to use esbuild with Deno, but you will need a plugin if you would like to be able to bundle HTTP URLs.

**Comment by ryanleecode** [comment]
I got rid of 

```
const { Deno: Deno1  } = globalThis;
typeof Deno1?.noColor === "boolean" ? Deno1.noColor : true;
```

and that seems to fix the Deno not defined error. However looking into the bundled output, it doesn't seem correct since the execution code uses `ArrayRune` but the bundled code the class is ArrayRune1

**Comment by harrysolovay** [comment]
> Deno team recommends using esbuild so will be looking into that

This sounds correct. The `bundle` command was deprecated as of 8h ago [see here](https://github.com/denoland/deno/pull/17695). For now, let's use esbuild. Eventually, perhaps we'll be able to use a built-in [`pack`](https://github.com/denoland/deno/issues/15463) command (if the Deno team decides to pursue it).

**Comment by tjjfvi** [comment]
We should test with `deno_emit` before we test with esbuild, but ideally we test with both. `deno_emit` will test `deno -> browser` (as we use Capi in fresh etc.), and esbuild will test `deno -> node -> browser`.


> ```ts
> const { Deno: Deno1  } = globalThis;
> typeof Deno1?.noColor === "boolean" ? Deno1.noColor : true;
> ```

There's no reason this should be causing a "Deno not defined" error. It can be run in the browser just fine.

> However looking into the bundled output, it doesn't seem correct since the execution code uses `ArrayRune` but the bundled code the class is `ArrayRune1`

This is just how bundling works; identifiers may get renamed, but it shouldn't change anything.

**Comment by ryanleecode** [comment]
> We should test with `deno_emit` before we test with esbuild, but ideally we test with both. `deno_emit` will test `deno -> browser` (as we use Capi in fresh on the Apps team), and esbuild will test `deno -> node -> browser`.
> 
> > ```ts
> > const { Deno: Deno1  } = globalThis;
> > typeof Deno1?.noColor === "boolean" ? Deno1.noColor : true;
> > ```
> 
> There's no reason this should be causing a "Deno not defined" error. It can be run in the browser just fine.
> 
> > However looking into the bundled output, it doesn't seem correct since the execution code uses `ArrayRune` but the bundled code the class is `ArrayRune1`
> 
> This is just how bundling works; identifiers may get renamed, but it shouldn't change anything.
I get this when running it in the browser

![image](https://user-images.githubusercontent.com/21375952/221213328-6fa29c5e-3d47-43d7-9a67-ea5c53f3b4ed.png)

**Comment by ryanleecode** [comment]
looking at using this https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action and we can feed params using the github actions yaml file instead of via CLI and report success or failure through the github actions API instead of using a deno test.

**Comment by harrysolovay** [comment]
Do you mean using `core.setFailed`, etc.? What advantage does this serve over using Deno's assertions? And might we sometimes want to run the tests locally?

**Comment by ryanleecode** [comment]
> Do you mean using `core.setFailed`, etc.? What advantage does this serve over using Deno's assertions? And might we sometimes want to run the tests locally?

Yes exactly we will be using `core.setFailed`. Going with the Deno test approach didnt seem feasible because if you are going to "codegen" tests you need to know where the relative directory for imports are going to be. i.e. where is `../deps/std/io.ts`. And we cant have `Deno.test` inside of the tool itself since it lives _outside_ of the repository its operating in.

**Comment by ryanleecode** [comment]
> Do you mean using `core.setFailed`, etc.? What advantage does this serve over using Deno's assertions? And might we sometimes want to run the tests locally?

There are always to run gh actions locally.

https://github.com/nektos/act

**Comment by harrysolovay** [comment]
While we could, I don't think we'd want to depend on a local actions simulator. Let's think about the error reporting last. If we can minimally transpile and execute tests via puppeteer, we'll be in good shape.

**Comment by ryanleecode** [comment]
I suspect there is something wrong with how zombienet chains are stood up and shutdown. When running the examples all in parallel, the script fails to exit at the end -- leads me to believe theres a hanging process thats not shutdown. 

```
done running examples
[
  [ "indices.ts", 0 ],
  [ "bonded.ts", 0 ],
  [ "era_rewards.ts", 0 ],
  [ "batch.ts", 0 ],
  [ "multisig_pure_proxy_stash.ts", 1 ],
  [ "error_unhandling.ts", 1 ],
  [ "fee_estimate.ts", 0 ],
  [ "balance.ts", 0 ],
  [ "entry_page.ts", 0 ],
  [ "polkadot_js_signer.ts", 0 ],
  [ "watch.ts", 0 ],
  [ "transfer_sequence.ts", 0 ],
  [ "xcm_asset_teleportation.ts", 1 ],
  [ "derived.ts", 0 ],
  [ "identity_cr.ts", 0 ],
  [ "block_events.ts", 0 ],
  [ "metadata.ts", 0 ],
  [ "virtual_multisig.ts", 1 ],
  [ "first_ten_keys.ts", 0 ],
  [ "block_extrinsics.ts", 0 ],
  [ "size_tree.ts", 0 ],
  [ "block_author.ts", 0 ],
  [ "transfer.ts", 0 ]
]
```

My tests showed the `xcm_asset_teleportation.ts` test failing with exitcode 1 and when i ran all the tests again without this one the script was able to exit.

**Comment by harrysolovay** [comment]
@kratico thoughts on this?

**Comment by kratico** [comment]
I haven't found the root cause.
I'd suggest to ignore the xcm test (which is the only one that uses zombienet) and check if the `star` task is stable again in CI
I have observed a similar thing here https://github.com/paritytech/capi/actions/runs/4387581033/jobs/7683049755#step:6:170

This could be related to computing resources (I'll add this to my debug checklist)
