### ISSUE TITLE
`dbg` and `log` in Runes

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#573]
- Should we have both?
- How does one disable `dbg`? #517?
- Should it be accessible only on `ValueRune` or on all?

**Comment by tjjfvi** [comment]
`dbg` is for temporary, printf-style debugging. One should never commit uses of `dbg`.

`log` is for intentional logs, like what we do in `logEvent`. Committing this makes sense.

Disabling `dbg` doesn't make sense, as if there's a `dbg` call, it must be intentional for the current context. Disabling `log` does make sense, and yes, will be handled via env.

Exposing it on classes other than `ValueRune` isn't really feasible at the moment.

**Comment by ryanleecode** [comment]
We should add the ability to use a custom logger for `log`

**Comment by tjjfvi** [comment]
Yes, this will be done via env.

**Comment by harrysolovay** [comment]
For context #517
