### ISSUE TITLE
confirm lack of usefulness of event topics

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#576]
I couldn't find any mention of event topics in the PJS codebase nor the substrate docs. According to an offline convo with @jsdw, the intended utility of a topic is supplemented by basic filtering of events based on the extrinsic index (which Capi already does). Not sure if there's any additional utility to come from event topics... in any case, please comment here if you have any thoughts on where/if topics can be useful to the Capi DX.

**Comment by jsdw** [comment]
Well; I mean I think we can filter on events already by filtering on pallet etc index, but to be honest I can only guess at what the original point of topics was; the impression I got was simply that they were added for some reason but never really used and possibly not supported/useful at present.

**Comment by josepot** [comment]
I just would like to explain how incredibly useful "event topics" have been for building a decentralized exchange on top of Ethereum, and why I think that _perhaps_ Substrate may want to consider having better support for "event topics".

I'm well aware that the set of trade offs are completely different in Substrate, and that perhaps there are better ways to accomplish the same thing on Substrate without having to abuse "event topics", in the way that we did on Ethereum. So, please, if that's the case I would really like to hear your thoughts on this matter.

The last few months I've been helping at building the [contango.xyz](https://beta.contango.xyz/) dApp. One of the biggest accomplishment has been IMO to be able to have a fully decentralized exchange that doesn't rely on "The Graph" (or any other indexer tools) for displaying the user's positions (and the history of changes of those positions), while at the same time being very, very frugal with the amount of data that it's stored on-chain. Which, as you can imagine, greatly reduces the amount of gas spent on the different transactions that a user can perform. All this has been possible thanks to the fact that we have modeled the events of the Contango contracts so that they can be used from the dApp in order to derive all the critical information that it's relevant to the user, but that we don't need to store on-chain. It almost feels like cheating TBH :joy: :shrug: 

For instance, the open/active positions are stored on-chain, ofc, but they just have most-basic and relevant information. Like, the Contango contracts don't even have an enumerable extension. So, it's not possible to make a `eth_call` in order to pull all the open positions for a given address. However, as you can imagine, this is a critical functionality for the dApp and for the users: we need to know the active-positions for a given address, right? So, what we do is we query the relevant events by topic (through [`eth_getLogs`](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs)) and we derive the rest of the info on the dApp. Believe it or not, this is incredibly fast and efficient. And you may be thinking: what about institutional traders that have thousands of open positions for a given address? wouldn't the `eth_getLogs` calls blow up for those addresses? And, yeah, probably that's true... However, the dApp is  currently meant for retail, so not a real concern ATM.

Maybe another thing that I should mention is that the Contango dApp is not using the standard "Ethereum Web3 tooling" (ethers.js/web3.js), but rather my humble creation (unstoppablejs), which is a lot lighter and it -aparently- much better serves the particular needs of this dApp. The reason why I'm mentioning this, is not to brag about my humble WIP creation, but to explain that I'm fairly familiar with the Ethereum Contract ABI spec and also with the Ethereum JSON-RPC API spec, since I had to rely on those in order to create abstractions on top of them for unstoppablejs.

Based on that knowledge, I think  that I can say that in Ethereum "event topics" are IMO "first class citizens". As they are [well defined in the Contract ABI spec](https://docs.soliditylang.org/en/v0.8.17/abi-spec.html#events) and there are [many critical endpoints in the Ethereum JSON-RPC API](https://ethereum.org/en/developers/docs/apis/json-rpc) to leverage them. So, I built a fair amount of utils and abstractions around those on the solidity-bindings of unstoppablejs.

Then, later -when I wanted to bring some of those abstractions and utils back into the substrate-bindings that I have for unstoppablejs- I kinda assumed that Substrate was going to have even better support for "event topics", but I was a bit shocked (and kinda disapointed?) to see that was not the case.

I even [opened this question on substrate.exchange](https://substrate.stackexchange.com/questions/5563/is-there-a-json-rpc-method-similar-to-eth-getlogs). And after digging around for a bit I realized that it was [technically possible to store "indexed events" using Substrate](https://github.com/paritytech/substrate/blob/676e35fdfdd2526a2df29efd41e6642046f2ddee/frame/system/src/lib.rs#L1231-L1236). However, that functionality seems to be disabled by default? My super-limited understanding is that in Substrate the way of consuming "event topics" is to query the storage `system.eventTopics` which has a vector of a tuple with the blocks-indexes for a the given topic? So, if that's the case, then there is some very basic support, I guess. However, it seems quite impractical to effectively leverage that.

Anyways, please understand that I'm not here to say that Substrate sucks b/c of its lack of support for "event topics". I'm sure that there must be a reason for that. Perhaps, the answer is just that we don't need to rely on events so heavily b/c SCALE is much more efficient when it comes to encode data. So, maybe on Substrate we can just afford to store more stuff on-chain rather than relying on logs so heavily? I don't know. I'm just thinking out-loud... I'm just a mere FE developer :sweat_smile: However, if anyone could please help me understand why "event topics" are not "first class citizens" on Substrate, I would greatly appreciate that! :pray:

**Comment by harrysolovay** [comment]
> So, IMO there is no need to create an extra metadata field that gets attached into the extrinsic

Makes complete sense. Probably best to steer clear of front-end devs deciding on grouping anyways, as this would be insecure (someone could pretend that their tx belongs to a given group).

> So, that later it's easier to query all the transactions that a wallet has received (or sent), after a certain block. Do you see what I mean?

Yes, this also makes sense. Thank you for this info!

Any advice on how it would be best to proceed in Capi? Might we want to create "virtual" topics that somewhat mimic the functionality we're looking for?

**Comment by harrysolovay** [comment]
@josepot thank you again for the incredible feedback.

Going to close this as out of scope. Will revisit should some topic-related functionality become feasible.
