### ISSUE TITLE
add mapR or mapRune as a method to value rune to it explict.

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#578]
Given

 ```ts
const threshold = signatories.map(({ length }) => length - 1)
````

 without knowing the types before hand (i.e. you are reviewing this right off of github, its hard to tell whether you are operating over an array or over a `ValueRune`, in this case it is a ValueRune<Uint8Array[]>`. We should have a method like `mapR` which does the same thing as `map` but it lets the programmer make it explict that its operating over a Rune rather than an array.

i.e. 

 ```ts
const threshold = signatories.mapR(({ length }) => length - 1)
````

**Comment by tjjfvi** [comment]
Conceptually, mapping over an `Array<Foo>` and a `Rune<Foo>` are rather similar (they're both a standard functor map). If you really need to distinguish, you can tell pretty easily by looking at where `signatories` was defined (which, in good code, shouldn't be far away).

We certainly shouldn't have both `map` and `mapR`, as the choice of which to use would be arbitrary. Then, it's a question of what methods to name with a postfix `R` – again, the choice is arbitrary. I don't think it's worthwhile to make all methods post-fixed with `R`, and so I don't think any should be.

The main solution to this problem would be hungarian notation on runes, like we do with codecs. We've gone over different notations for naming runes a million times, and we've always settled on no prefix being best.

**Comment by ryanleecode** [comment]
We may also consider having static variants of these methods. Hence if I want to make it explictly that i am operating over a ValueRune i can do

`ValueRune.map(myValueRune, (x) => {})`

**Comment by tjjfvi** [comment]
Having multiple ways to do the same thing is generally bad, as it adds cognitive overhead.

For this case, I would recommend disambiguating it by writing
```ts
const threshold = signatories.map((sigs) => sigs.length - 1)
```
